import { Injectable } from '@angular/core';

export interface Model {
  id: string;
  name: string;
  playgroundUrl: string;
  vendorSpecificId: string;
}

@Injectable({
  providedIn: 'root',
})
export class ModelService {
  private models: Model[] = [
    { name: "Generic", playgroundUrl: "", id: "generic", vendorSpecificId: "" },
    { name: "OpenAI Gpt 4 0613", playgroundUrl: "https://chat.openai.com/?model=gpt-4-0613&q={prompt}", id: "openapi-gpt-4-0613", vendorSpecificId: "gpt-4-0613" },
    { name: "OpenAI Gpt 5.2 Chat Latest", playgroundUrl: "https://chat.openai.com/?model=gpt-5.2-chat-latest&q={prompt}", id: "openapi-gpt-5.2-chat-latest", vendorSpecificId: "gpt-5.2-chat-latest" },
    { name: "OpenAI Gpt 5.2 2025 12 11", playgroundUrl: "https://chat.openai.com/?model=gpt-5.2-2025-12-11&q={prompt}", id: "openapi-gpt-5.2-2025-12-11", vendorSpecificId: "gpt-5.2-2025-12-11" },
    { name: "OpenAI Gpt 5.2", playgroundUrl: "https://chat.openai.com/?model=gpt-5.2&q={prompt}", id: "openapi-gpt-5.2", vendorSpecificId: "gpt-5.2" },
    { name: "OpenAI Gpt 5.2 Pro 2025 12 11", playgroundUrl: "https://chat.openai.com/?model=gpt-5.2-pro-2025-12-11&q={prompt}", id: "openapi-gpt-5.2-pro-2025-12-11", vendorSpecificId: "gpt-5.2-pro-2025-12-11" },
    { name: "OpenAI Gpt 5.2 Pro", playgroundUrl: "https://chat.openai.com/?model=gpt-5.2-pro&q={prompt}", id: "openapi-gpt-5.2-pro", vendorSpecificId: "gpt-5.2-pro" },
    { name: "OpenAI Davinci 002", playgroundUrl: "https://chat.openai.com/?model=davinci-002&q={prompt}", id: "openapi-davinci-002", vendorSpecificId: "davinci-002" },
    { name: "OpenAI Babbage 002", playgroundUrl: "https://chat.openai.com/?model=babbage-002&q={prompt}", id: "openapi-babbage-002", vendorSpecificId: "babbage-002" },
    { name: "OpenAI Gpt 3.5 Turbo Instruct", playgroundUrl: "https://chat.openai.com/?model=gpt-3.5-turbo-instruct&q={prompt}", id: "openapi-gpt-3.5-turbo-instruct", vendorSpecificId: "gpt-3.5-turbo-instruct" },
    { name: "OpenAI Gpt 3.5 Turbo Instruct 0914", playgroundUrl: "https://chat.openai.com/?model=gpt-3.5-turbo-instruct-0914&q={prompt}", id: "openapi-gpt-3.5-turbo-instruct-0914", vendorSpecificId: "gpt-3.5-turbo-instruct-0914" },
    { name: "OpenAI Dall E 3", playgroundUrl: "https://chat.openai.com/?model=dall-e-3&q={prompt}", id: "openapi-dall-e-3", vendorSpecificId: "dall-e-3" },
    { name: "OpenAI Dall E 2", playgroundUrl: "https://chat.openai.com/?model=dall-e-2&q={prompt}", id: "openapi-dall-e-2", vendorSpecificId: "dall-e-2" },
    { name: "OpenAI Gpt 4 1106 Preview", playgroundUrl: "https://chat.openai.com/?model=gpt-4-1106-preview&q={prompt}", id: "openapi-gpt-4-1106-preview", vendorSpecificId: "gpt-4-1106-preview" },
    { name: "OpenAI Gpt 3.5 Turbo 1106", playgroundUrl: "https://chat.openai.com/?model=gpt-3.5-turbo-1106&q={prompt}", id: "openapi-gpt-3.5-turbo-1106", vendorSpecificId: "gpt-3.5-turbo-1106" },
    { name: "OpenAI Tts 1 Hd", playgroundUrl: "https://chat.openai.com/?model=tts-1-hd&q={prompt}", id: "openapi-tts-1-hd", vendorSpecificId: "tts-1-hd" },
    { name: "OpenAI Tts 1 1106", playgroundUrl: "https://chat.openai.com/?model=tts-1-1106&q={prompt}", id: "openapi-tts-1-1106", vendorSpecificId: "tts-1-1106" },
    { name: "OpenAI Tts 1 Hd 1106", playgroundUrl: "https://chat.openai.com/?model=tts-1-hd-1106&q={prompt}", id: "openapi-tts-1-hd-1106", vendorSpecificId: "tts-1-hd-1106" },
    { name: "OpenAI Text Embedding 3 Small", playgroundUrl: "https://chat.openai.com/?model=text-embedding-3-small&q={prompt}", id: "openapi-text-embedding-3-small", vendorSpecificId: "text-embedding-3-small" },
    { name: "OpenAI Text Embedding 3 Large", playgroundUrl: "https://chat.openai.com/?model=text-embedding-3-large&q={prompt}", id: "openapi-text-embedding-3-large", vendorSpecificId: "text-embedding-3-large" },
    { name: "OpenAI Gpt 4 0125 Preview", playgroundUrl: "https://chat.openai.com/?model=gpt-4-0125-preview&q={prompt}", id: "openapi-gpt-4-0125-preview", vendorSpecificId: "gpt-4-0125-preview" },
    { name: "OpenAI Gpt 4 Turbo Preview", playgroundUrl: "https://chat.openai.com/?model=gpt-4-turbo-preview&q={prompt}", id: "openapi-gpt-4-turbo-preview", vendorSpecificId: "gpt-4-turbo-preview" },
    { name: "OpenAI Gpt 3.5 Turbo 0125", playgroundUrl: "https://chat.openai.com/?model=gpt-3.5-turbo-0125&q={prompt}", id: "openapi-gpt-3.5-turbo-0125", vendorSpecificId: "gpt-3.5-turbo-0125" },
    { name: "OpenAI Gpt 4 Turbo", playgroundUrl: "https://chat.openai.com/?model=gpt-4-turbo&q={prompt}", id: "openapi-gpt-4-turbo", vendorSpecificId: "gpt-4-turbo" },
    { name: "OpenAI Gpt 4 Turbo 2024 04 09", playgroundUrl: "https://chat.openai.com/?model=gpt-4-turbo-2024-04-09&q={prompt}", id: "openapi-gpt-4-turbo-2024-04-09", vendorSpecificId: "gpt-4-turbo-2024-04-09" },
    { name: "OpenAI Gpt 4o", playgroundUrl: "https://chat.openai.com/?model=gpt-4o&q={prompt}", id: "openapi-gpt-4o", vendorSpecificId: "gpt-4o" },
    { name: "OpenAI Gpt 4o 2024 05 13", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-2024-05-13&q={prompt}", id: "openapi-gpt-4o-2024-05-13", vendorSpecificId: "gpt-4o-2024-05-13" },
    { name: "OpenAI Gpt 4o Mini 2024 07 18", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-mini-2024-07-18&q={prompt}", id: "openapi-gpt-4o-mini-2024-07-18", vendorSpecificId: "gpt-4o-mini-2024-07-18" },
    { name: "OpenAI Gpt 4o Mini", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-mini&q={prompt}", id: "openapi-gpt-4o-mini", vendorSpecificId: "gpt-4o-mini" },
    { name: "OpenAI Gpt 4o 2024 08 06", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-2024-08-06&q={prompt}", id: "openapi-gpt-4o-2024-08-06", vendorSpecificId: "gpt-4o-2024-08-06" },
    { name: "OpenAI Chatgpt 4o Latest", playgroundUrl: "https://chat.openai.com/?model=chatgpt-4o-latest&q={prompt}", id: "openapi-chatgpt-4o-latest", vendorSpecificId: "chatgpt-4o-latest" },
    { name: "OpenAI Gpt 4o Audio Preview", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-audio-preview&q={prompt}", id: "openapi-gpt-4o-audio-preview", vendorSpecificId: "gpt-4o-audio-preview" },
    { name: "OpenAI Gpt 4o Realtime Preview", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-realtime-preview&q={prompt}", id: "openapi-gpt-4o-realtime-preview", vendorSpecificId: "gpt-4o-realtime-preview" },
    { name: "OpenAI Omni Moderation Latest", playgroundUrl: "https://chat.openai.com/?model=omni-moderation-latest&q={prompt}", id: "openapi-omni-moderation-latest", vendorSpecificId: "omni-moderation-latest" },
    { name: "OpenAI Omni Moderation 2024 09 26", playgroundUrl: "https://chat.openai.com/?model=omni-moderation-2024-09-26&q={prompt}", id: "openapi-omni-moderation-2024-09-26", vendorSpecificId: "omni-moderation-2024-09-26" },
    { name: "OpenAI Gpt 4o Realtime Preview 2024 12 17", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-realtime-preview-2024-12-17&q={prompt}", id: "openapi-gpt-4o-realtime-preview-2024-12-17", vendorSpecificId: "gpt-4o-realtime-preview-2024-12-17" },
    { name: "OpenAI Gpt 4o Audio Preview 2024 12 17", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-audio-preview-2024-12-17&q={prompt}", id: "openapi-gpt-4o-audio-preview-2024-12-17", vendorSpecificId: "gpt-4o-audio-preview-2024-12-17" },
    { name: "OpenAI Gpt 4o Mini Realtime Preview 2024 12 17", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-mini-realtime-preview-2024-12-17&q={prompt}", id: "openapi-gpt-4o-mini-realtime-preview-2024-12-17", vendorSpecificId: "gpt-4o-mini-realtime-preview-2024-12-17" },
    { name: "OpenAI Gpt 4o Mini Audio Preview 2024 12 17", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-mini-audio-preview-2024-12-17&q={prompt}", id: "openapi-gpt-4o-mini-audio-preview-2024-12-17", vendorSpecificId: "gpt-4o-mini-audio-preview-2024-12-17" },
    { name: "OpenAI O1 2024 12 17", playgroundUrl: "https://chat.openai.com/?model=o1-2024-12-17&q={prompt}", id: "openapi-o1-2024-12-17", vendorSpecificId: "o1-2024-12-17" },
    { name: "OpenAI O1", playgroundUrl: "https://chat.openai.com/?model=o1&q={prompt}", id: "openapi-o1", vendorSpecificId: "o1" },
    { name: "OpenAI Gpt 4o Mini Realtime Preview", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-mini-realtime-preview&q={prompt}", id: "openapi-gpt-4o-mini-realtime-preview", vendorSpecificId: "gpt-4o-mini-realtime-preview" },
    { name: "OpenAI Gpt 4o Mini Audio Preview", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-mini-audio-preview&q={prompt}", id: "openapi-gpt-4o-mini-audio-preview", vendorSpecificId: "gpt-4o-mini-audio-preview" },
    { name: "OpenAI O3 Mini", playgroundUrl: "https://chat.openai.com/?model=o3-mini&q={prompt}", id: "openapi-o3-mini", vendorSpecificId: "o3-mini" },
    { name: "OpenAI O3 Mini 2025 01 31", playgroundUrl: "https://chat.openai.com/?model=o3-mini-2025-01-31&q={prompt}", id: "openapi-o3-mini-2025-01-31", vendorSpecificId: "o3-mini-2025-01-31" },
    { name: "OpenAI Gpt 4o 2024 11 20", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-2024-11-20&q={prompt}", id: "openapi-gpt-4o-2024-11-20", vendorSpecificId: "gpt-4o-2024-11-20" },
    { name: "OpenAI Gpt 4o Search Preview 2025 03 11", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-search-preview-2025-03-11&q={prompt}", id: "openapi-gpt-4o-search-preview-2025-03-11", vendorSpecificId: "gpt-4o-search-preview-2025-03-11" },
    { name: "OpenAI Gpt 4o Search Preview", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-search-preview&q={prompt}", id: "openapi-gpt-4o-search-preview", vendorSpecificId: "gpt-4o-search-preview" },
    { name: "OpenAI Gpt 4o Mini Search Preview 2025 03 11", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-mini-search-preview-2025-03-11&q={prompt}", id: "openapi-gpt-4o-mini-search-preview-2025-03-11", vendorSpecificId: "gpt-4o-mini-search-preview-2025-03-11" },
    { name: "OpenAI Gpt 4o Mini Search Preview", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-mini-search-preview&q={prompt}", id: "openapi-gpt-4o-mini-search-preview", vendorSpecificId: "gpt-4o-mini-search-preview" },
    { name: "OpenAI Gpt 4o Transcribe", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-transcribe&q={prompt}", id: "openapi-gpt-4o-transcribe", vendorSpecificId: "gpt-4o-transcribe" },
    { name: "OpenAI Gpt 4o Mini Transcribe", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-mini-transcribe&q={prompt}", id: "openapi-gpt-4o-mini-transcribe", vendorSpecificId: "gpt-4o-mini-transcribe" },
    { name: "OpenAI O1 Pro 2025 03 19", playgroundUrl: "https://chat.openai.com/?model=o1-pro-2025-03-19&q={prompt}", id: "openapi-o1-pro-2025-03-19", vendorSpecificId: "o1-pro-2025-03-19" },
    { name: "OpenAI O1 Pro", playgroundUrl: "https://chat.openai.com/?model=o1-pro&q={prompt}", id: "openapi-o1-pro", vendorSpecificId: "o1-pro" },
    { name: "OpenAI Gpt 4o Mini Tts", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-mini-tts&q={prompt}", id: "openapi-gpt-4o-mini-tts", vendorSpecificId: "gpt-4o-mini-tts" },
    { name: "OpenAI O3 2025 04 16", playgroundUrl: "https://chat.openai.com/?model=o3-2025-04-16&q={prompt}", id: "openapi-o3-2025-04-16", vendorSpecificId: "o3-2025-04-16" },
    { name: "OpenAI O4 Mini 2025 04 16", playgroundUrl: "https://chat.openai.com/?model=o4-mini-2025-04-16&q={prompt}", id: "openapi-o4-mini-2025-04-16", vendorSpecificId: "o4-mini-2025-04-16" },
    { name: "OpenAI O3", playgroundUrl: "https://chat.openai.com/?model=o3&q={prompt}", id: "openapi-o3", vendorSpecificId: "o3" },
    { name: "OpenAI O4 Mini", playgroundUrl: "https://chat.openai.com/?model=o4-mini&q={prompt}", id: "openapi-o4-mini", vendorSpecificId: "o4-mini" },
    { name: "OpenAI Gpt 4.1 2025 04 14", playgroundUrl: "https://chat.openai.com/?model=gpt-4.1-2025-04-14&q={prompt}", id: "openapi-gpt-4.1-2025-04-14", vendorSpecificId: "gpt-4.1-2025-04-14" },
    { name: "OpenAI Gpt 4.1", playgroundUrl: "https://chat.openai.com/?model=gpt-4.1&q={prompt}", id: "openapi-gpt-4.1", vendorSpecificId: "gpt-4.1" },
    { name: "OpenAI Gpt 4.1 Mini 2025 04 14", playgroundUrl: "https://chat.openai.com/?model=gpt-4.1-mini-2025-04-14&q={prompt}", id: "openapi-gpt-4.1-mini-2025-04-14", vendorSpecificId: "gpt-4.1-mini-2025-04-14" },
    { name: "OpenAI Gpt 4.1 Mini", playgroundUrl: "https://chat.openai.com/?model=gpt-4.1-mini&q={prompt}", id: "openapi-gpt-4.1-mini", vendorSpecificId: "gpt-4.1-mini" },
    { name: "OpenAI Gpt 4.1 Nano 2025 04 14", playgroundUrl: "https://chat.openai.com/?model=gpt-4.1-nano-2025-04-14&q={prompt}", id: "openapi-gpt-4.1-nano-2025-04-14", vendorSpecificId: "gpt-4.1-nano-2025-04-14" },
    { name: "OpenAI Gpt 4.1 Nano", playgroundUrl: "https://chat.openai.com/?model=gpt-4.1-nano&q={prompt}", id: "openapi-gpt-4.1-nano", vendorSpecificId: "gpt-4.1-nano" },
    { name: "OpenAI Gpt Image 1", playgroundUrl: "https://chat.openai.com/?model=gpt-image-1&q={prompt}", id: "openapi-gpt-image-1", vendorSpecificId: "gpt-image-1" },
    { name: "OpenAI Codex Mini Latest", playgroundUrl: "https://chat.openai.com/?model=codex-mini-latest&q={prompt}", id: "openapi-codex-mini-latest", vendorSpecificId: "codex-mini-latest" },
    { name: "OpenAI Gpt 4o Realtime Preview 2025 06 03", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-realtime-preview-2025-06-03&q={prompt}", id: "openapi-gpt-4o-realtime-preview-2025-06-03", vendorSpecificId: "gpt-4o-realtime-preview-2025-06-03" },
    { name: "OpenAI Gpt 4o Audio Preview 2025 06 03", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-audio-preview-2025-06-03&q={prompt}", id: "openapi-gpt-4o-audio-preview-2025-06-03", vendorSpecificId: "gpt-4o-audio-preview-2025-06-03" },
    { name: "OpenAI O4 Mini Deep Research", playgroundUrl: "https://chat.openai.com/?model=o4-mini-deep-research&q={prompt}", id: "openapi-o4-mini-deep-research", vendorSpecificId: "o4-mini-deep-research" },
    { name: "OpenAI Gpt 4o Transcribe Diarize", playgroundUrl: "https://chat.openai.com/?model=gpt-4o-transcribe-diarize&q={prompt}", id: "openapi-gpt-4o-transcribe-diarize", vendorSpecificId: "gpt-4o-transcribe-diarize" },
    { name: "OpenAI O4 Mini Deep Research 2025 06 26", playgroundUrl: "https://chat.openai.com/?model=o4-mini-deep-research-2025-06-26&q={prompt}", id: "openapi-o4-mini-deep-research-2025-06-26", vendorSpecificId: "o4-mini-deep-research-2025-06-26" },
    { name: "OpenAI Gpt 5 Chat Latest", playgroundUrl: "https://chat.openai.com/?model=gpt-5-chat-latest&q={prompt}", id: "openapi-gpt-5-chat-latest", vendorSpecificId: "gpt-5-chat-latest" },
    { name: "OpenAI Gpt 5 2025 08 07", playgroundUrl: "https://chat.openai.com/?model=gpt-5-2025-08-07&q={prompt}", id: "openapi-gpt-5-2025-08-07", vendorSpecificId: "gpt-5-2025-08-07" },
    { name: "OpenAI Gpt 5", playgroundUrl: "https://chat.openai.com/?model=gpt-5&q={prompt}", id: "openapi-gpt-5", vendorSpecificId: "gpt-5" },
    { name: "OpenAI Gpt 5 Mini 2025 08 07", playgroundUrl: "https://chat.openai.com/?model=gpt-5-mini-2025-08-07&q={prompt}", id: "openapi-gpt-5-mini-2025-08-07", vendorSpecificId: "gpt-5-mini-2025-08-07" },
    { name: "OpenAI Gpt 5 Mini", playgroundUrl: "https://chat.openai.com/?model=gpt-5-mini&q={prompt}", id: "openapi-gpt-5-mini", vendorSpecificId: "gpt-5-mini" },
    { name: "OpenAI Gpt 5 Nano 2025 08 07", playgroundUrl: "https://chat.openai.com/?model=gpt-5-nano-2025-08-07&q={prompt}", id: "openapi-gpt-5-nano-2025-08-07", vendorSpecificId: "gpt-5-nano-2025-08-07" },
    { name: "OpenAI Gpt 5 Nano", playgroundUrl: "https://chat.openai.com/?model=gpt-5-nano&q={prompt}", id: "openapi-gpt-5-nano", vendorSpecificId: "gpt-5-nano" },
    { name: "OpenAI Gpt Audio 2025 08 28", playgroundUrl: "https://chat.openai.com/?model=gpt-audio-2025-08-28&q={prompt}", id: "openapi-gpt-audio-2025-08-28", vendorSpecificId: "gpt-audio-2025-08-28" },
    { name: "OpenAI Gpt Realtime", playgroundUrl: "https://chat.openai.com/?model=gpt-realtime&q={prompt}", id: "openapi-gpt-realtime", vendorSpecificId: "gpt-realtime" },
    { name: "OpenAI Gpt Realtime 2025 08 28", playgroundUrl: "https://chat.openai.com/?model=gpt-realtime-2025-08-28&q={prompt}", id: "openapi-gpt-realtime-2025-08-28", vendorSpecificId: "gpt-realtime-2025-08-28" },
    { name: "OpenAI Gpt Audio", playgroundUrl: "https://chat.openai.com/?model=gpt-audio&q={prompt}", id: "openapi-gpt-audio", vendorSpecificId: "gpt-audio" },
    { name: "OpenAI Gpt 5 Codex", playgroundUrl: "https://chat.openai.com/?model=gpt-5-codex&q={prompt}", id: "openapi-gpt-5-codex", vendorSpecificId: "gpt-5-codex" },
    { name: "OpenAI Gpt Image 1 Mini", playgroundUrl: "https://chat.openai.com/?model=gpt-image-1-mini&q={prompt}", id: "openapi-gpt-image-1-mini", vendorSpecificId: "gpt-image-1-mini" },
    { name: "OpenAI Gpt 5 Pro 2025 10 06", playgroundUrl: "https://chat.openai.com/?model=gpt-5-pro-2025-10-06&q={prompt}", id: "openapi-gpt-5-pro-2025-10-06", vendorSpecificId: "gpt-5-pro-2025-10-06" },
    { name: "OpenAI Gpt 5 Pro", playgroundUrl: "https://chat.openai.com/?model=gpt-5-pro&q={prompt}", id: "openapi-gpt-5-pro", vendorSpecificId: "gpt-5-pro" },
    { name: "OpenAI Gpt Audio Mini", playgroundUrl: "https://chat.openai.com/?model=gpt-audio-mini&q={prompt}", id: "openapi-gpt-audio-mini", vendorSpecificId: "gpt-audio-mini" },
    { name: "OpenAI Gpt Audio Mini 2025 10 06", playgroundUrl: "https://chat.openai.com/?model=gpt-audio-mini-2025-10-06&q={prompt}", id: "openapi-gpt-audio-mini-2025-10-06", vendorSpecificId: "gpt-audio-mini-2025-10-06" },
    { name: "OpenAI Gpt 5 Search Api", playgroundUrl: "https://chat.openai.com/?model=gpt-5-search-api&q={prompt}", id: "openapi-gpt-5-search-api", vendorSpecificId: "gpt-5-search-api" },
    { name: "OpenAI Gpt Realtime Mini", playgroundUrl: "https://chat.openai.com/?model=gpt-realtime-mini&q={prompt}", id: "openapi-gpt-realtime-mini", vendorSpecificId: "gpt-realtime-mini" },
    { name: "OpenAI Gpt Realtime Mini 2025 10 06", playgroundUrl: "https://chat.openai.com/?model=gpt-realtime-mini-2025-10-06&q={prompt}", id: "openapi-gpt-realtime-mini-2025-10-06", vendorSpecificId: "gpt-realtime-mini-2025-10-06" },
    { name: "OpenAI Sora 2", playgroundUrl: "https://chat.openai.com/?model=sora-2&q={prompt}", id: "openapi-sora-2", vendorSpecificId: "sora-2" },
    { name: "OpenAI Sora 2 Pro", playgroundUrl: "https://chat.openai.com/?model=sora-2-pro&q={prompt}", id: "openapi-sora-2-pro", vendorSpecificId: "sora-2-pro" },
    { name: "OpenAI Gpt 5 Search Api 2025 10 14", playgroundUrl: "https://chat.openai.com/?model=gpt-5-search-api-2025-10-14&q={prompt}", id: "openapi-gpt-5-search-api-2025-10-14", vendorSpecificId: "gpt-5-search-api-2025-10-14" },
    { name: "OpenAI Gpt 5.1 Chat Latest", playgroundUrl: "https://chat.openai.com/?model=gpt-5.1-chat-latest&q={prompt}", id: "openapi-gpt-5.1-chat-latest", vendorSpecificId: "gpt-5.1-chat-latest" },
    { name: "OpenAI Gpt 5.1 2025 11 13", playgroundUrl: "https://chat.openai.com/?model=gpt-5.1-2025-11-13&q={prompt}", id: "openapi-gpt-5.1-2025-11-13", vendorSpecificId: "gpt-5.1-2025-11-13" },
    { name: "OpenAI Gpt 5.1", playgroundUrl: "https://chat.openai.com/?model=gpt-5.1&q={prompt}", id: "openapi-gpt-5.1", vendorSpecificId: "gpt-5.1" },
    { name: "OpenAI Gpt 5.1 Codex", playgroundUrl: "https://chat.openai.com/?model=gpt-5.1-codex&q={prompt}", id: "openapi-gpt-5.1-codex", vendorSpecificId: "gpt-5.1-codex" },
    { name: "OpenAI Gpt 5.1 Codex Mini", playgroundUrl: "https://chat.openai.com/?model=gpt-5.1-codex-mini&q={prompt}", id: "openapi-gpt-5.1-codex-mini", vendorSpecificId: "gpt-5.1-codex-mini" },
    { name: "OpenAI Gpt 5.1 Codex Max", playgroundUrl: "https://chat.openai.com/?model=gpt-5.1-codex-max&q={prompt}", id: "openapi-gpt-5.1-codex-max", vendorSpecificId: "gpt-5.1-codex-max" },
    { name: "Google BERT", playgroundUrl: "", id: "google-bert", vendorSpecificId: "" },
    { name: "Google T5", playgroundUrl: "", id: "google-t5", vendorSpecificId: "" },
    { name: "Google LaMDA", playgroundUrl: "", id: "google-lamda", vendorSpecificId: "" },
    { name: "Google PaLM", playgroundUrl: "", id: "google-palm", vendorSpecificId: "" },
    { name: "Google PaLM 2", playgroundUrl: "", id: "google-palm-2", vendorSpecificId: "" },
    { name: "Google Minerva", playgroundUrl: "", id: "google-minerva", vendorSpecificId: "" },
    { name: "Google Gemini 1.0 Nano-1", playgroundUrl: "", id: "google-gemini-1-0-nano-1", vendorSpecificId: "" },
    { name: "Google Gemini 1.0 Nano-2", playgroundUrl: "", id: "google-gemini-1-0-nano-2", vendorSpecificId: "" },
    { name: "Google Gemini 1.0 Pro", playgroundUrl: "", id: "google-gemini-1-0-pro", vendorSpecificId: "" },
    { name: "Google Gemini 1.0 Ultra", playgroundUrl: "", id: "google-gemini-1-0-ultra", vendorSpecificId: "" },
    { name: "Google Gemini 1.5 Pro", playgroundUrl: "", id: "google-gemini-1-5-pro", vendorSpecificId: "" },
    { name: "Google Gemini 1.5 Flash", playgroundUrl: "", id: "google-gemini-1-5-flash", vendorSpecificId: "" },
    { name: "Google Gemini 2.0 Flash", playgroundUrl: "", id: "google-gemini-2-0-flash", vendorSpecificId: "" },
    { name: "Google Gemini 2.0 Flash-Lite", playgroundUrl: "", id: "google-gemini-2-0-flash-lite", vendorSpecificId: "" },
    { name: "Google Gemini 2.5 Pro", playgroundUrl: "", id: "google-gemini-2-5-pro", vendorSpecificId: "" },
    { name: "Google Gemini 2.5 Flash", playgroundUrl: "", id: "google-gemini-2-5-flash", vendorSpecificId: "" },
    { name: "Google Gemini 2.5 Flash-Lite", playgroundUrl: "", id: "google-gemini-2-5-flash-lite", vendorSpecificId: "" },
    { name: "Google Gemini 2.5 Flash Image", playgroundUrl: "", id: "google-gemini-2-5-flash-image", vendorSpecificId: "" },
    { name: "Google Gemini 2.5 Flash Gemini Live API", playgroundUrl: "", id: "google-gemini-2-5-flash-gemini-live-api", vendorSpecificId: "" },
    { name: "Google Gemini 3 Pro", playgroundUrl: "", id: "google-gemini-3-pro", vendorSpecificId: "" },
    { name: "Google Gemini 3 Pro Image", playgroundUrl: "", id: "google-gemini-3-pro-image", vendorSpecificId: "" },
    { name: "Google Nano Banana", playgroundUrl: "", id: "google-nano-banana", vendorSpecificId: "" },
    { name: "Google Nano Banana Pro", playgroundUrl: "", id: "google-nano-banana-pro", vendorSpecificId: "" },
    { name: "Google Imagen", playgroundUrl: "", id: "google-imagen", vendorSpecificId: "" },
    { name: "Google Veo", playgroundUrl: "", id: "google-veo", vendorSpecificId: "" },
    { name: "Google Veo 3.1", playgroundUrl: "", id: "google-veo-3-1", vendorSpecificId: "" },
    { name: "Google Veo 3.1 Fast", playgroundUrl: "", id: "google-veo-3-1-fast", vendorSpecificId: "" },
    { name: "Google Lyria", playgroundUrl: "", id: "google-lyria", vendorSpecificId: "" },
    { name: "Google SIMA", playgroundUrl: "", id: "google-sima", vendorSpecificId: "" },
    { name: "Google MedLM-large-large", playgroundUrl: "", id: "google-medlm-large-large", vendorSpecificId: "" },
    { name: "Google Gemma 2B", playgroundUrl: "", id: "google-gemma-2b", vendorSpecificId: "" },
    { name: "Google Gemma 7B", playgroundUrl: "", id: "google-gemma-7b", vendorSpecificId: "" },
    { name: "Google Gemma 3 (4B)", playgroundUrl: "", id: "google-gemma-3-4b", vendorSpecificId: "" },
    { name: "Google Gemma 3 (27B)", playgroundUrl: "", id: "google-gemma-3-27b", vendorSpecificId: "" },
    { name: "Google CodeGemma", playgroundUrl: "", id: "google-codegemma", vendorSpecificId: "" },
    { name: "Google PaliGemma", playgroundUrl: "", id: "google-paligemma", vendorSpecificId: "" },
    { name: "Google PaliGemma 2", playgroundUrl: "", id: "google-paligemma-2", vendorSpecificId: "" },
    { name: "Google TxGemma", playgroundUrl: "", id: "google-txgemma", vendorSpecificId: "" },
    { name: "Google ShieldGemma 2", playgroundUrl: "", id: "google-shieldgemma-2", vendorSpecificId: "" },
    { name: "Google WeatherNext 2", playgroundUrl: "", id: "google-weathernext-2", vendorSpecificId: "" },
    { name: "Anthropic Claude v1", playgroundUrl: "", id: "anthropic-claude-v1", vendorSpecificId: "" },
    { name: "Anthropic Claude 2", playgroundUrl: "", id: "anthropic-claude-2", vendorSpecificId: "" },
    { name: "Anthropic Claude 2.1", playgroundUrl: "", id: "anthropic-claude-2-1", vendorSpecificId: "" },
    { name: "Anthropic Claude 3 Haiku", playgroundUrl: "", id: "anthropic-claude-3-haiku", vendorSpecificId: "" },
    { name: "Anthropic Claude 3 Sonnet", playgroundUrl: "", id: "anthropic-claude-3-sonnet", vendorSpecificId: "" },
    { name: "Anthropic Claude 3 Opus", playgroundUrl: "", id: "anthropic-claude-3-opus", vendorSpecificId: "" },
    { name: "Anthropic Claude 3.5 Sonnet", playgroundUrl: "", id: "anthropic-claude-3-5-sonnet", vendorSpecificId: "" },
    { name: "Anthropic Claude 3.5 Haiku", playgroundUrl: "", id: "anthropic-claude-3-5-haiku", vendorSpecificId: "" },
    { name: "Anthropic Claude 3.7 Sonnet", playgroundUrl: "", id: "anthropic-claude-3-7-sonnet", vendorSpecificId: "" },
    { name: "Anthropic Claude 4 Opus", playgroundUrl: "", id: "anthropic-claude-4-opus", vendorSpecificId: "" },
    { name: "Anthropic Claude 4 Sonnet", playgroundUrl: "", id: "anthropic-claude-4-sonnet", vendorSpecificId: "" },
    { name: "Anthropic Claude 4.5 Haiku", playgroundUrl: "", id: "anthropic-claude-4-5-haiku", vendorSpecificId: "" },
    { name: "Anthropic Claude 4.5 Sonnet", playgroundUrl: "", id: "anthropic-claude-4-5-sonnet", vendorSpecificId: "" },
    { name: "Anthropic Claude 4.5 Opus", playgroundUrl: "", id: "anthropic-claude-4-5-opus", vendorSpecificId: "" },
    { name: "Meta AI LLaMA", playgroundUrl: "", id: "meta-ai-llama", vendorSpecificId: "" },
    { name: "Meta AI Llama 2 (7B)", playgroundUrl: "", id: "meta-ai-llama-2-7b", vendorSpecificId: "" },
    { name: "Meta AI Llama 2 (13B)", playgroundUrl: "", id: "meta-ai-llama-2-13b", vendorSpecificId: "" },
    { name: "Meta AI Llama 2 (70B)", playgroundUrl: "", id: "meta-ai-llama-2-70b", vendorSpecificId: "" },
    { name: "Meta AI Code Llama (7B)", playgroundUrl: "", id: "meta-ai-code-llama-7b", vendorSpecificId: "" },
    { name: "Meta AI Code Llama (13B)", playgroundUrl: "", id: "meta-ai-code-llama-13b", vendorSpecificId: "" },
    { name: "Meta AI Code Llama (34B)", playgroundUrl: "", id: "meta-ai-code-llama-34b", vendorSpecificId: "" },
    { name: "Meta AI Code Llama (70B)", playgroundUrl: "", id: "meta-ai-code-llama-70b", vendorSpecificId: "" },
    { name: "Meta AI Llama 3 (8B)", playgroundUrl: "", id: "meta-ai-llama-3-8b", vendorSpecificId: "" },
    { name: "Meta AI Llama 3 (70B)", playgroundUrl: "", id: "meta-ai-llama-3-70b", vendorSpecificId: "" },
    { name: "Meta AI Llama 3.1 (8B)", playgroundUrl: "", id: "meta-ai-llama-3-1-8b", vendorSpecificId: "" },
    { name: "Meta AI Llama 3.1 (70B)", playgroundUrl: "", id: "meta-ai-llama-3-1-70b", vendorSpecificId: "" },
    { name: "Meta AI Llama 3.1 (405B)", playgroundUrl: "", id: "meta-ai-llama-3-1-405b", vendorSpecificId: "" },
    { name: "Meta AI Llama 3.2 (1B)", playgroundUrl: "", id: "meta-ai-llama-3-2-1b", vendorSpecificId: "" },
    { name: "Meta AI Llama 3.2 (3B)", playgroundUrl: "", id: "meta-ai-llama-3-2-3b", vendorSpecificId: "" },
    { name: "Meta AI Llama 3.2 Vision (11B)", playgroundUrl: "", id: "meta-ai-llama-3-2-vision-11b", vendorSpecificId: "" },
    { name: "Meta AI Llama 3.2 Vision (90B)", playgroundUrl: "", id: "meta-ai-llama-3-2-vision-90b", vendorSpecificId: "" },
    { name: "Meta AI Llama 3.3 (70B)", playgroundUrl: "", id: "meta-ai-llama-3-3-70b", vendorSpecificId: "" },
    { name: "Meta AI Llama 4 Scout", playgroundUrl: "", id: "meta-ai-llama-4-scout", vendorSpecificId: "" },
    { name: "Meta AI Llama 4 Maverick", playgroundUrl: "", id: "meta-ai-llama-4-maverick", vendorSpecificId: "" },
    { name: "Meta AI Llama 4 Behemoth", playgroundUrl: "", id: "meta-ai-llama-4-behemoth", vendorSpecificId: "" },
    { name: "Meta AI Llama Guard 3", playgroundUrl: "", id: "meta-ai-llama-guard-3", vendorSpecificId: "" },
    { name: "Meta AI Emu", playgroundUrl: "", id: "meta-ai-emu", vendorSpecificId: "" },
    { name: "Mistral AI Mistral 7B (v0.1)", playgroundUrl: "", id: "mistral-ai-mistral-7b-v0-1", vendorSpecificId: "" },
    { name: "Mistral AI Mistral 7B (v0.2)", playgroundUrl: "", id: "mistral-ai-mistral-7b-v0-2", vendorSpecificId: "" },
    { name: "Mistral AI Mistral 7B (v0.3)", playgroundUrl: "", id: "mistral-ai-mistral-7b-v0-3", vendorSpecificId: "" },
    { name: "Mistral AI Mistral Small 1.0", playgroundUrl: "", id: "mistral-ai-mistral-small-1-0", vendorSpecificId: "" },
    { name: "Mistral AI Mistral Small 2.0", playgroundUrl: "", id: "mistral-ai-mistral-small-2-0", vendorSpecificId: "" },
    { name: "Mistral AI Mistral Small 3.1", playgroundUrl: "", id: "mistral-ai-mistral-small-3-1", vendorSpecificId: "" },
    { name: "Mistral AI Mistral Small 3.2", playgroundUrl: "", id: "mistral-ai-mistral-small-3-2", vendorSpecificId: "" },
    { name: "Mistral AI Mistral Medium 1.0", playgroundUrl: "", id: "mistral-ai-mistral-medium-1-0", vendorSpecificId: "" },
  ];

  getModels(): Model[] {
    return this.models;
  }

  getModelById(id: string): Model | undefined {
    return this.models.find(model => model.id === id);
  }
}
